/* Generated By:JavaCC: Do not edit this line. StatMCrulesConstants.java */
package ParserStatMC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StatMCrulesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int FLOAT_SCIENTIFIC = 9;
  /** RegularExpression Id. */
  int EXPONENT = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int WORD = 13;
  /** RegularExpression Id. */
  int SECTION_AGENTS = 14;
  /** RegularExpression Id. */
  int SECTION_PROPERTY = 15;
  /** RegularExpression Id. */
  int SYMBOL_PROP = 16;
  /** RegularExpression Id. */
  int SYMBOL_PROP_COUNT = 17;
  /** RegularExpression Id. */
  int KEYWORD_GEQ = 18;
  /** RegularExpression Id. */
  int KEYWORD_LEQ = 19;
  /** RegularExpression Id. */
  int EOL = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int DEFINE = 24;
  /** RegularExpression Id. */
  int ASSIGN = 25;
  /** RegularExpression Id. */
  int LSQ = 26;
  /** RegularExpression Id. */
  int RSQ = 27;
  /** RegularExpression Id. */
  int LR = 28;
  /** RegularExpression Id. */
  int RR = 29;
  /** RegularExpression Id. */
  int QUO = 30;
  /** RegularExpression Id. */
  int SQUO = 31;
  /** RegularExpression Id. */
  int EXCL = 32;
  /** RegularExpression Id. */
  int LBRAC = 33;
  /** RegularExpression Id. */
  int RBRAC = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int LANG = 36;
  /** RegularExpression Id. */
  int RANG = 37;
  /** RegularExpression Id. */
  int PARALLEL = 38;
  /** RegularExpression Id. */
  int DASH = 39;
  /** RegularExpression Id. */
  int UP = 40;
  /** RegularExpression Id. */
  int DOWN = 41;
  /** RegularExpression Id. */
  int INT = 42;
  /** RegularExpression Id. */
  int DOUBLE = 43;
  /** RegularExpression Id. */
  int IDENTIFIER = 44;
  /** RegularExpression Id. */
  int MATH_EXPR = 45;
  /** RegularExpression Id. */
  int SPACE = 46;
  /** RegularExpression Id. */
  int M_AND = 47;
  /** RegularExpression Id. */
  int M_OR = 48;
  /** RegularExpression Id. */
  int M_LINER = 49;
  /** RegularExpression Id. */
  int M_LINEN = 50;
  /** RegularExpression Id. */
  int SYMBOL = 51;
  /** RegularExpression Id. */
  int PARAM_SYMBOL = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int RESET = 1;
  /** Lexical state. */
  int ID = 2;
  /** Lexical state. */
  int MATH = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<FLOAT>",
    "<FLOAT_SCIENTIFIC>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIGIT>",
    "<WORD>",
    "\"#Agents\"",
    "\"#Property\"",
    "\"A(l)\"",
    "\"#A(l)\"",
    "\">=\"",
    "\"<=\"",
    "\";\"",
    "\"+\"",
    "\".\"",
    "\":\"",
    "\":=\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"||\"",
    "\"-\"",
    "\">>\"",
    "\"<<\"",
    "<INT>",
    "<DOUBLE>",
    "<IDENTIFIER>",
    "<MATH_EXPR>",
    "<SPACE>",
    "\"&&\"",
    "\"|\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SYMBOL>",
    "<PARAM_SYMBOL>",
  };

}
