/* Generated By:JavaCC: Do not edit this line. MELAprog2Constants.java */
package ParserProg2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MELAprog2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int FLOAT_SCIENTIFIC = 9;
  /** RegularExpression Id. */
  int EXPONENT = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int WORD = 13;
  /** RegularExpression Id. */
  int SECTION_PARAM = 14;
  /** RegularExpression Id. */
  int SECTION_AGENTS = 15;
  /** RegularExpression Id. */
  int SECTION_ENV = 16;
  /** RegularExpression Id. */
  int SECTION_INIT = 17;
  /** RegularExpression Id. */
  int KEYWORD_LOC = 18;
  /** RegularExpression Id. */
  int KEYWORD_NEIGH = 19;
  /** RegularExpression Id. */
  int KEYWORD_ALL = 20;
  /** RegularExpression Id. */
  int INFSET = 21;
  /** RegularExpression Id. */
  int EOL = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int DOT = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;
  /** RegularExpression Id. */
  int DOLLAR = 26;
  /** RegularExpression Id. */
  int DEFINE = 27;
  /** RegularExpression Id. */
  int ASSIGN = 28;
  /** RegularExpression Id. */
  int LSQ = 29;
  /** RegularExpression Id. */
  int RSQ = 30;
  /** RegularExpression Id. */
  int LR = 31;
  /** RegularExpression Id. */
  int RR = 32;
  /** RegularExpression Id. */
  int QUO = 33;
  /** RegularExpression Id. */
  int SQUO = 34;
  /** RegularExpression Id. */
  int QUEST = 35;
  /** RegularExpression Id. */
  int EXCL = 36;
  /** RegularExpression Id. */
  int AT = 37;
  /** RegularExpression Id. */
  int LBRAC = 38;
  /** RegularExpression Id. */
  int RBRAC = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int LANG = 41;
  /** RegularExpression Id. */
  int RANG = 42;
  /** RegularExpression Id. */
  int PARALLEL = 43;
  /** RegularExpression Id. */
  int UPARROW = 44;
  /** RegularExpression Id. */
  int DOWNARROW = 45;
  /** RegularExpression Id. */
  int DASH = 46;
  /** RegularExpression Id. */
  int MELASYMBOL = 47;
  /** RegularExpression Id. */
  int INT = 48;
  /** RegularExpression Id. */
  int DOUBLE = 49;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;
  /** RegularExpression Id. */
  int UPDATE_LOC = 51;
  /** RegularExpression Id. */
  int MATH_EXPR = 52;
  /** RegularExpression Id. */
  int SPACE = 53;
  /** RegularExpression Id. */
  int M_AND = 54;
  /** RegularExpression Id. */
  int M_OR = 55;
  /** RegularExpression Id. */
  int M_LINER = 56;
  /** RegularExpression Id. */
  int M_LINEN = 57;
  /** RegularExpression Id. */
  int MATH_PARAM = 58;
  /** RegularExpression Id. */
  int SYMBOL = 59;
  /** RegularExpression Id. */
  int PARAM_SYMBOL = 60;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int RESET = 1;
  /** Lexical state. */
  int ID = 2;
  /** Lexical state. */
  int MATH = 3;
  /** Lexical state. */
  int SIMPLE_MATH = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<FLOAT>",
    "<FLOAT_SCIENTIFIC>",
    "<EXPONENT>",
    "<LETTER>",
    "<DIGIT>",
    "<WORD>",
    "\"#Parameters\"",
    "\"#Agents\"",
    "\"#Environment\"",
    "\"#Initial conditions\"",
    "\"l\"",
    "\"N(l)\"",
    "\"all\"",
    "<INFSET>",
    "\";\"",
    "\"+\"",
    "\".\"",
    "\":\"",
    "\"$\"",
    "\":=\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"?\"",
    "\"!\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"||\"",
    "\">>\"",
    "\"<<\"",
    "\"-\"",
    "<MELASYMBOL>",
    "<INT>",
    "<DOUBLE>",
    "<IDENTIFIER>",
    "<UPDATE_LOC>",
    "<MATH_EXPR>",
    "<SPACE>",
    "\"&&\"",
    "\"|\"",
    "\"\\r\"",
    "\"\\n\"",
    "<MATH_PARAM>",
    "<SYMBOL>",
    "<PARAM_SYMBOL>",
  };

}
